getgenv().CNF = {
    Webhook_Fish = "https://discordapp.com/api/webhooks/1461657990418661471/YP8dG8zbMLIBVxgYoYRuAKLyyJMwoPRO4gSOPEQC1gOU6svc98vfmT_Qugq6GAytf3HQ",
    Webhook_Leave = "https://discordapp.com/api/webhooks/1461658096832086079/J-FHRV1vkFLIwXVIlM2HltDmbokfwh9OCN90tlkF9qen2m-Y2Q1rmqpBGj43hYAKsJQF",

    SecretList = {
        "Crystal Crab",
        "Orca",
        "Zombie Shark",
        "Zombie Megalodon",
        "Dead Zombie Shark",
        "Blob Shark",
        "Ghost Shark",
        "Skeleton Narwhal",
        "Ghost Worm Fish",
        "Worm Fish",
        "Megalodon",
        "1x1x1x1 Comet Shark",
        "Bloodmoon Whale",
        "Lochness Monster",
        "Monster Shark",
        "Eerie Shark",
        "Great Whale",
        "Frostborn Shark",
        "Armored Shark",
        "Scare",
        "Queen Crab",
        "King Crab",
        "Cryoshade Glider",
        "Panther Eel",
        "Giant Squid",
        "Depthseeker Ray",
        "Robot Kraken",
        "Mosasaur Shark",
        "King Jelly",
        "Bone Whale",
        "Elshark Gran Maja",
        "Ancient Whale",
        "Gladiator Shark",
        "Ancient Lochness Monster",
        "Talon Serpent",
        "Hacker Shark",
        "ElRetro Gran Maja",
        "Strawberry Choc Megalodon",
        "Krampus Shark",
        "Emerald Winter Whale",
        "Winter Frost Shark",
        "Icebreaker Whale",
        "Leviathan",
        "Pirate Megalodon",
    },

    StoneList = {
        "Ruby",
    }
}

loadstring(game:HttpGet("https://raw.githubusercontent.com/xalparfume/AL/refs/heads/main/xal.lua"))()
